"""added unique constraint for org and bill number

Revision ID: 8ad9046226b9
Revises: f7fe7b382d06
Create Date: 2022-11-18 00:22:38.817157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ad9046226b9'
down_revision = 'f7fe7b382d06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_bills_org_id_number', 'bills', ['org_id', 'number'])
    op.drop_index('ix_orgs_name', table_name='orgs')
    op.create_index(op.f('ix_orgs_name'), 'orgs', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orgs_name'), table_name='orgs')
    op.create_index('ix_orgs_name', 'orgs', ['name'], unique=False)
    op.drop_constraint('uix_bills_org_id_number', 'bills', type_='unique')
    # ### end Alembic commands ###
